### ISSUE TITLE
(anchorScroll) Cannot read properties of undefined (reading 'top')

### ISSUE THREAD

**Issue by Nearata** [flarum/framework#3632]
### Current Behavior

```js
Uncaught TypeError: Cannot read properties of undefined (reading 'top')
    at oe (anchorScroll.js:16:37)
    at i (PostStreamState.ts:240:7)
    at e.loadPage (PostStreamState.ts:242:5)
    at e._loadPrevious (PostStreamState.ts:227:10)
    at f (throttle.js:67:13)
    at t.u [as loadPrevious] (throttle.js:93:4)
    at n.loadPostsIfNeeded (PostStream.js:182:21)
    at n.onscroll (PostStream.js:158:10)
    at e.update (ScrollListener.js:40:10)
    at ScrollListener.js:29:12
oe @ anchorScroll.js:16
i @ PostStreamState.ts:240
e.loadPage @ PostStreamState.ts:242
e._loadPrevious @ PostStreamState.ts:227
f @ throttle.js:67
u @ throttle.js:93
n.loadPostsIfNeeded @ PostStream.js:182
n.onscroll @ PostStream.js:158
e.update @ ScrollListener.js:40
(anonymous) @ ScrollListener.js:29
requestAnimationFrame (async)
e.loop @ ScrollListener.js:28
```

### Steps to Reproduce

1. go to a discussion with lot of posts
2. start deleting them like crazy

### Expected Behavior

im still not sure what this issue actually break

### Environment

- Flarum version: 1.4.1
- Website URL: local
- Webserver: nginx
- Hosting environment: local
- PHP version: 7.4.30
- Browser: brave 1.43.89

**Comment by SychO9** [comment]
Cannot reproduce, let us know if you encounter this again and the steps to reproduce. Thanks!
