### ISSUE TITLE
API Client breaks the forum if used in environment like Swoole and with extension that need some values from server params

### ISSUE THREAD

**Issue by YUCLing** [flarum/framework#3981]
### Current Behavior

In environments like Swoole, `$_SERVER`'s values are different from normal web server environment.

To run Flarum properly in Swoole, server params will be constructed by Swoole application and passed to Flarum using `ServerRequest`.

Everything will work if nothing else goes wrong, but in `Flarum\Api\Client`, `ServerRequestFactory::fromGlobals` is used. This causes the request created by this client contains nothing from Swoole's server params. With some combination of extensions, forum will be broken.

The combination in my case is:
- Blomstra Search
- Discussion Views

It ended up with an exception saying `SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'ip' cannot be null`.

### Steps to Reproduce

1. Create a Swoole application that boots Flarum and serves requests for Flarum.
2. Install Blomstra Search and Discussion View extension and configure them properly.
3. Open up a discussion page in browser

### Expected Behavior

The discussion page shows up without any errors.

### Screenshots

No screenshots available since the whole page content is empty.

### Environment

- Flarum version: 1.8.5
- Website URL: Local test env
- Webserver: Swoole
- Hosting environment: Docker container on my PC
- PHP version: 8.3.2
- Browser: chrome 123

### Output of `php flarum info`

```
Flarum core: 1.8.5
PHP version: 8.3.2
MySQL version: 11.3.2-MariaDB-1:11.3.2+maria~ubu2204
Loaded extensions: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, hash, iconv, json, mbstring, SPL, session, PDO, pdo_sqlite, standard, posix, random, readline, Reflection, Phar, SimpleXML, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, exif, gd, imagick, pdo_mysql, redis, sockets, sodium, swoole
+---------------------------------+------------+--------+
| Flarum Extensions               |            |        |
+---------------------------------+------------+--------+
| ID                              | Version    | Commit |
+---------------------------------+------------+--------+
| flarum-flags                    | v1.8.0     |        |
| flarum-tags                     | v1.8.0     |        |
| flarum-approval                 | v1.8.1     |        |
| flarum-mentions                 | v1.8.3     |        |
| flarum-subscriptions            | v1.8.0     |        |
| flarum-sticky                   | v1.8.0     |        |
| flarum-likes                    | v1.8.0     |        |
| flarum-suspend                  | v1.8.1     |        |
| fof-follow-tags                 | 1.2.2      |        |
| zequeen-acgembed-remastered     | v1.1.2     |        |
| v17development-seo              | v1.8.1     |        |
| the-turk-stickiest              | 3.0.1      |        |
| swaggymacro-only-starter        | 0.6.6      |        |
| rhodes-island-oauth-center      | 1.1.3      |        |
| michaelbelgium-discussion-views | v7.2.1     |        |
| fof-user-bio                    | 1.3.2      |        |
| fof-upload                      | 1.5.4      |        |
| fof-sitemap                     | 2.2.1      |        |
| fof-sentry                      | 1.3.2      |        |
| fof-secure-https                | 1.1.3      |        |
| fof-reactions                   | 1.4.1      |        |
| fof-profile-image-crop          | 1.1.6      |        |
| fof-pretty-mail                 | 1.1.2      |        |
| fof-polls                       | 2.1.2      |        |
| fof-nightmode                   | 1.5.3      |        |
| fof-links                       | 1.2.3      |        |
| fof-linguist                    | 1.1.2      |        |
| fof-impersonate                 | 1.1.1      |        |
| fof-formatting                  | 1.0.3      |        |
| fof-drafts                      | 1.2.10     |        |
| fof-best-answer                 | 1.4.2      |        |
| flarum-statistics               | v1.8.0     |        |
| flarum-pusher                   | v1.8.0     |        |
| flarum-nicknames                | v1.8.0     |        |
| flarum-markdown                 | v1.8.0     |        |
| flarum-lock                     | v1.8.0     |        |
| flarum-lang-chinese-simplified  | dev-master |        |
| flarum-emoji                    | v1.8.0     |        |
| flarum-bbcode                   | v1.8.0     |        |
| ffans-clipboardjs               | v1.0.0     |        |
| darkle-fancybox                 | 1.1.3      |        |
| blomstra-search                 | 0.1.17     |        |
| blomstra-fontawesome            | 0.1.5      |        |
+---------------------------------+------------+--------+
Base URL: http://127.0.0.1:8183
Installation path: /var/www/web
Queue driver: redis
Session driver: redis (Code override. Configured to file)
Scheduler status: 未激活
Mail driver: smtp
Debug mode: off
```

### Possible Solution

Figure out a way to pass server params to Client.

### Additional Context

Notice that Flarum\Api\Client is used, and from its code [here](https://github.com/flarum/framework/blob/9149ecc7aad62c592c070664c1ec503b025a9e00/framework/core/src/Api/Client.php#L117) we can see it's not using request's server params.
```
[2024-04-20 16:20:45] flarum.ERROR: PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'ip' cannot be null in /var/www/web/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117
Stack trace:
#0 /var/www/web/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(117): PDOStatement->execute()
#1 /var/www/web/vendor/illuminate/database/Connection.php(501): Doctrine\DBAL\Driver\PDOStatement->execute()
#2 /var/www/web/vendor/illuminate/database/Connection.php(705): Illuminate\Database\Connection->Illuminate\Database\{closure}()
#3 /var/www/web/vendor/illuminate/database/Connection.php(672): Illuminate\Database\Connection->runQueryCallback()
#4 /var/www/web/vendor/illuminate/database/Connection.php(490): Illuminate\Database\Connection->run()
#5 /var/www/web/vendor/illuminate/database/Connection.php(454): Illuminate\Database\Connection->statement()
#6 /var/www/web/vendor/illuminate/database/Query/Processors/Processor.php(32): Illuminate\Database\Connection->insert()
#7 /var/www/web/vendor/illuminate/database/Query/Builder.php(3028): Illuminate\Database\Query\Processors\Processor->processInsertGetId()
#8 /var/www/web/vendor/illuminate/database/Eloquent/Builder.php(1657): Illuminate\Database\Query\Builder->insertGetId()
#9 /var/www/web/vendor/illuminate/database/Eloquent/Model.php(1188): Illuminate\Database\Eloquent\Builder->__call()
#10 /var/www/web/vendor/illuminate/database/Eloquent/Model.php(1153): Illuminate\Database\Eloquent\Model->insertAndSetId()
#11 /var/www/web/vendor/illuminate/database/Eloquent/Model.php(994): Illuminate\Database\Eloquent\Model->performInsert()
#12 /var/www/web/vendor/illuminate/database/Eloquent/Relations/HasOneOrMany.php(267): Illuminate\Database\Eloquent\Model->save()
#13 /var/www/web/vendor/michaelbelgium/flarum-discussion-views/src/Listeners/AddDiscussionViewHandler.php(59): Illuminate\Database\Eloquent\Relations\HasOneOrMany->save()
#14 /var/www/web/vendor/flarum/core/src/Foundation/ContainerUtil.php(30): Michaelbelgium\Discussionviews\Listeners\AddDiscussionViewHandler->__invoke()
#15 /var/www/web/vendor/flarum/core/src/Api/Controller/AbstractSerializeController.php(121): Flarum\Foundation\ContainerUtil::Flarum\Foundation\{closure}()
#16 /var/www/web/vendor/flarum/core/src/Http/RouteHandlerFactory.php(41): Flarum\Api\Controller\AbstractSerializeController->handle()
#17 /var/www/web/vendor/flarum/core/src/Http/Middleware/ExecuteRoute.php(27): Flarum\Http\RouteHandlerFactory->Flarum\Http\{closure}()
#18 /var/www/web/vendor/laminas/laminas-stratigility/src/Next.php(50): Flarum\Http\Middleware\ExecuteRoute->process()
#19 /var/www/web/vendor/fof/reactions/src/Middleware/BindRequestToContainer.php(35): Laminas\Stratigility\Next->handle()
#20 /var/www/web/vendor/laminas/laminas-stratigility/src/Next.php(50): FoF\Reactions\Middleware\BindRequestToContainer->process()
#21 /var/www/web/vendor/fof/sentry/src/Middleware/HandleErrorsWithSentry.php(39): Laminas\Stratigility\Next->handle()
#22 /var/www/web/vendor/laminas/laminas-stratigility/src/Next.php(50): FoF\Sentry\Middleware\HandleErrorsWithSentry->process()
#23 /var/www/web/vendor/flarum/core/src/Api/Middleware/ThrottleApi.php(33): Laminas\Stratigility\Next->handle()
#24 /var/www/web/vendor/laminas/laminas-stratigility/src/Next.php(50): Flarum\Api\Middleware\ThrottleApi->process()
#25 /var/www/web/vendor/flarum/core/src/Http/Middleware/ResolveRoute.php(69): Laminas\Stratigility\Next->handle()
#26 /var/www/web/vendor/laminas/laminas-stratigility/src/Next.php(50): Flarum\Http\Middleware\ResolveRoute->process()
#27 /var/www/web/vendor/flarum/core/src/Http/Middleware/SetLocale.php(51): Laminas\Stratigility\Next->handle()
#28 /var/www/web/vendor/laminas/laminas-stratigility/src/Next.php(50): Flarum\Http\Middleware\SetLocale->process()
#29 /var/www/web/vendor/rhodes-island/flarum-oauth-center/src/Middlewares/ResourceScopeMiddleware.php(33): Laminas\Stratigility\Next->handle()
#30 /var/www/web/vendor/laminas/laminas-stratigility/src/Next.php(50): RhodesIsland\OAuthCenter\Middlewares\ResourceScopeMiddleware->process()
#31 /var/www/web/vendor/flarum/core/src/Http/Middleware/HandleErrors.php(57): Laminas\Stratigility\Next->handle()
#32 /var/www/web/vendor/laminas/laminas-stratigility/src/Next.php(50): Flarum\Http\Middleware\HandleErrors->process()
#33 /var/www/web/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(75): Laminas\Stratigility\Next->handle()
#34 /var/www/web/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(64): Laminas\Stratigility\MiddlewarePipe->process()
#35 /var/www/web/vendor/flarum/core/src/Api/Client.php(141): Laminas\Stratigility\MiddlewarePipe->handle()
#36 /var/www/web/vendor/flarum/core/src/Api/Client.php(91): Flarum\Api\Client->send()
#37 /var/www/web/vendor/blomstra/search/src/Api/Client.php(26): Flarum\Api\Client->get()
#38 /var/www/web/vendor/flarum/core/src/Forum/Content/Discussion.php(121): Blomstra\Search\Api\Client->get()
#39 /var/www/web/vendor/flarum/core/src/Forum/Content/Discussion.php(65): Flarum\Forum\Content\Discussion->getApiDocument()
#40 /var/www/web/vendor/flarum/core/src/Frontend/Frontend.php(62): Flarum\Forum\Content\Discussion->__invoke()
#41 /var/www/web/vendor/flarum/core/src/Frontend/Frontend.php(54): Flarum\Frontend\Frontend->populate()
#42 /var/www/web/vendor/flarum/core/src/Frontend/Controller.php(32): Flarum\Frontend\Frontend->document()
#43 /var/www/web/vendor/flarum/core/src/Http/RouteHandlerFactory.php(41): Flarum\Frontend\Controller->handle()
#44 /var/www/web/vendor/flarum/core/src/Http/Middleware/ExecuteRoute.php(27): Flarum\Http\RouteHandlerFactory->Flarum\Http\{closure}()
#45 /var/www/web/vendor/laminas/laminas-stratigility/src/Next.php(50): Flarum\Http\Middleware\ExecuteRoute->process()
#46 /var/www/web/vendor/fof/secure-https/src/Middlewares/ContentSecurityPolicyMiddleware.php(32): Laminas\Stratigility\Next->handle()
#47 /var/www/web/vendor/laminas/laminas-stratigility/src/Next.php(50): FoF\SecureHttps\Middlewares\ContentSecurityPolicyMiddleware->process()
#48 /var/www/web/vendor/fof/sentry/src/Middleware/HandleErrorsWithSentry.php(39): Laminas\Stratigility\Next->handle()
#49 /var/www/web/vendor/laminas/laminas-stratigility/src/Next.php(50): FoF\Sentry\Middleware\HandleErrorsWithSentry->process()
#50 /var/www/web/vendor/flarum/core/src/Http/Middleware/ContentTypeOptionsHeader.php(21): Laminas\Stratigility\Next->handle()
#51 /var/www/web/vendor/laminas/laminas-stratigility/src/Next.php(50): Flarum\Http\Middleware\ContentTypeOptionsHeader->process()
#52 /var/www/web/vendor/flarum/core/src/Http/Middleware/ReferrerPolicyHeader.php(30): Laminas\Stratigility\Next->handle()
#53 /var/www/web/vendor/laminas/laminas-stratigility/src/Next.php(50): Flarum\Http\Middleware\ReferrerPolicyHeader->process()
#54 /var/www/web/vendor/flarum/core/src/Http/Middleware/FlarumPromotionHeader.php(30): Laminas\Stratigility\Next->handle()
#55 /var/www/web/vendor/laminas/laminas-stratigility/src/Next.php(50): Flarum\Http\Middleware\FlarumPromotionHeader->process()
#56 /var/www/web/vendor/flarum/core/src/Http/Middleware/ShareErrorsFromSession.php(57): Laminas\Stratigility\Next->handle()
#57 /var/www/web/vendor/laminas/laminas-stratigility/src/Next.php(50): Flarum\Http\Middleware\ShareErrorsFromSession->process()
#58 /var/www/web/vendor/rhodes-island/flarum-oauth-center/src/Middlewares/UserCredentialsMiddleware.php(31): Laminas\Stratigility\Next->handle()
#59 /var/www/web/vendor/laminas/laminas-stratigility/src/Next.php(50): RhodesIsland\OAuthCenter\Middlewares\UserCredentialsMiddleware->process()
#60 /var/www/web/vendor/flarum/core/src/Http/Middleware/CheckCsrfToken.php(36): Laminas\Stratigility\Next->handle()
#61 /var/www/web/vendor/laminas/laminas-stratigility/src/Next.php(50): Flarum\Http\Middleware\CheckCsrfToken->process()
#62 /var/www/web/vendor/rhodes-island/flarum-oauth-center/src/Middlewares/UnsetCsrfMiddleware.php(23): Laminas\Stratigility\Next->handle()
#63 /var/www/web/vendor/laminas/laminas-stratigility/src/Next.php(50): RhodesIsland\OAuthCenter\Middlewares\UnsetCsrfMiddleware->process()
#64 /var/www/web/vendor/flarum/core/src/Http/Middleware/ResolveRoute.php(69): Laminas\Stratigility\Next->handle()
#65 /var/www/web/vendor/laminas/laminas-stratigility/src/Next.php(50): Flarum\Http\Middleware\ResolveRoute->process()
#66 /var/www/web/vendor/flarum/core/src/Http/Middleware/SetLocale.php(51): Laminas\Stratigility\Next->handle()
#67 /var/www/web/vendor/laminas/laminas-stratigility/src/Next.php(50): Flarum\Http\Middleware\SetLocale->process()
#68 /var/www/web/vendor/flarum/core/src/Http/Middleware/AuthenticateWithSession.php(31): Laminas\Stratigility\Next->handle()
#69 /var/www/web/vendor/laminas/laminas-stratigility/src/Next.php(50): Flarum\Http\Middleware\AuthenticateWithSession->process()
#70 /var/www/web/vendor/flarum/core/src/Http/Middleware/RememberFromCookie.php(52): Laminas\Stratigility\Next->handle()
#71 /var/www/web/vendor/laminas/laminas-stratigility/src/Next.php(50): Flarum\Http\Middleware\RememberFromCookie->process()
#72 /var/www/web/vendor/flarum/core/src/Http/Middleware/StartSession.php(61): Laminas\Stratigility\Next->handle()
#73 /var/www/web/vendor/laminas/laminas-stratigility/src/Next.php(50): Flarum\Http\Middleware\StartSession->process()
#74 /var/www/web/vendor/flarum/core/src/Http/Middleware/CollectGarbage.php(46): Laminas\Stratigility\Next->handle()
#75 /var/www/web/vendor/laminas/laminas-stratigility/src/Next.php(50): Flarum\Http\Middleware\CollectGarbage->process()
#76 /var/www/web/vendor/flarum/core/src/Http/Middleware/ParseJsonBody.php(28): Laminas\Stratigility\Next->handle()
#77 /var/www/web/vendor/laminas/laminas-stratigility/src/Next.php(50): Flarum\Http\Middleware\ParseJsonBody->process()
#78 /var/www/web/vendor/flarum/core/src/Http/Middleware/HandleErrors.php(57): Laminas\Stratigility\Next->handle()
#79 /var/www/web/vendor/laminas/laminas-stratigility/src/Next.php(50): Flarum\Http\Middleware\HandleErrors->process()
#80 /var/www/web/vendor/flarum/core/src/Http/Middleware/InjectActorReference.php(25): Laminas\Stratigility\Next->handle()
#81 /var/www/web/vendor/laminas/laminas-stratigility/src/Next.php(50): Flarum\Http\Middleware\InjectActorReference->process()
#82 /var/www/web/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(75): Laminas\Stratigility\Next->handle()
#83 /var/www/web/vendor/middlewares/request-handler/src/RequestHandler.php(84): Laminas\Stratigility\MiddlewarePipe->process()
#84 /var/www/web/vendor/laminas/laminas-stratigility/src/Next.php(50): Middlewares\RequestHandler->process()
#85 /var/www/web/vendor/middlewares/base-path-router/src/BasePathRouter.php(99): Laminas\Stratigility\Next->handle()
#86 /var/www/web/vendor/laminas/laminas-stratigility/src/Next.php(50): Middlewares\BasePathRouter->process()
#87 /var/www/web/vendor/laminas/laminas-stratigility/src/Middleware/OriginalMessages.php(36): Laminas\Stratigility\Next->handle()
#88 /var/www/web/vendor/laminas/laminas-stratigility/src/Next.php(50): Laminas\Stratigility\Middleware\OriginalMessages->process()
#89 /var/www/web/vendor/middlewares/base-path/src/BasePath.php(73): Laminas\Stratigility\Next->handle()
#90 /var/www/web/vendor/laminas/laminas-stratigility/src/Next.php(50): Middlewares\BasePath->process()
#91 /var/www/web/vendor/flarum/core/src/Http/Middleware/ProcessIp.php(24): Laminas\Stratigility\Next->handle()
#92 /var/www/web/vendor/laminas/laminas-stratigility/src/Next.php(50): Flarum\Http\Middleware\ProcessIp->process()
#93 /var/www/web/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(75): Laminas\Stratigility\Next->handle()
#94 /var/www/web/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(64): Laminas\Stratigility\MiddlewarePipe->process()
#95 /var/www/web/swoole.php(69): Laminas\Stratigility\MiddlewarePipe->handle()
#96 [internal function]: {closure}()
#97 {main}
```

**Comment by SychO9** [comment]
This is expected. Flarum is not yet ready to be run in async servers.

This is something we have in mind for the future, but we haven't gotten around to yet.

When Flarum is made officially compatible, there will be proper documentation on the matter 👍
